[package]
name = "whatiforbit-app"
version.workspace = true
edition.workspace = true

[[bin]]
name = "whatiforbit"
path = "src/main.rs"

[dependencies]
whatiforbit-sim = { path = "../sim-core" }
glam = { workspace = true }
hifitime = { workspace = true }
bevy = { version = "0.16", features = ["jpeg"] }
bevy_egui = "0.36"
ehttp = "0.7"

[target.'cfg(target_arch = "wasm32")'.dependencies]
bevy = { version = "0.16", features = ["webgl2"] }
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
    "Window",
    "Location",
    "History",
    "Blob",
    "Url",
    "Document",
    "Element",
    "HtmlElement",
    "HtmlAnchorElement",
] }
